#!/bin/bash

export LANG=en_US.UTF-8
WEBROOT=${WEBROOT:-$HOME/www}

function timestamp {
    date "+%Y%m%d %H:%M %z"
}
function unix_timestamp {
    date "+%s"
}

function melpa {
    timestamp

    timestamp > $WEBROOT/status.txt
    echo "building..." >> $WEBROOT/status.txt

    MELPADIR=${MELPADIR:-$HOME/melpa}
    MELPABRANCH=${MELPABRANCH:-`git rev-parse --abbrev-ref HEAD`}

    PATH=$HOME/.cabal/bin:$HOME/usr/bin:$HOME/bin:$PATH

    [[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

    STDOUT=`mktemp`
    STDERR=`mktemp`

    env &>> ${STDOUT}

    ## git pull
    cd ${MELPADIR}
    git fetch origin &>> ${STDOUT}
    git reset --hard origin/${MELPABRANCH} &>> ${STDOUT}
    git pull origin ${MELPABRANCH} &>> ${STDOUT}
    echo >> ${STDOUT}

    ## run the script
    cd ${MELPADIR}
    grep --files-with-match wiki recipes/* | xargs -n 4 make -j2 &
    grep --files-without-match wiki recipes/* | xargs -n 8 make -j4
    wait

    make packages/archive-contents
    make json
    make index

    ## sync to the web directory
    rsync -avz --delete ${MELPADIR}/packages ${MELPADIR}/html/. ${WEBROOT}/ 1>> ${STDOUT} 2>> ${STDERR}

    chmod -R go+rx ${WEBROOT}/packages/*

    /usr/sbin/logrotate -s $HOME/log/logrotate.state $HOME/log/melpa.logrotate 1>> ${STDOUT} 2>> ${STDERR}

    EMAIL=`mktemp`
    echo "Subject: Melpa status `timestamp`" > ${EMAIL}
    cat ${STDOUT} ${STDERR} >> ${EMAIL}

    /usr/sbin/sendmail dcurtis@milkbox.net < ${EMAIL}
    cat ${ENVLOG} ${STDERR} ${STDOUT} | tee $WEBROOT/lastrun.txt

    timestamp > $WEBROOT/status.txt
    echo "completed" >> $WEBROOT/status.txt
    echo '{"completed":' `unix_timestamp` '}' > $WEBROOT/build-status.json
}

melpa
